### ISSUE TITLE
FEAT : 현재 디렉토리 파일 받기

### ISSUE THREAD

**Issue by Giromi** [Oris482/Minishell#15]
![image](https://user-images.githubusercontent.com/60354633/187101914-d2e85dd2-138d-45d9-86be-a458737ad772.png)

### 메모리 누수 관련
https://bodamnury.tistory.com/17
![image](https://user-images.githubusercontent.com/60354633/187101985-3a0b8173-ef93-4036-a48e-d588a6f851c1.png)

readdir함수 free 안해도 됨.

**Comment by Oris482** [comment]
dirent_utils.c
