### ISSUE TITLE
BUG: 괄호 안닫힌거 인식이 제대로 안됨

### ISSUE THREAD

**Issue by Oris482** [Oris482/Minishell#27]
((hello) => 에러로 인식이 안됨
앞에서 켠 플래그가 뒤에 닫는 괄호 하나로 다 꺼져버리는 듯

**Comment by Giromi** [comment]
으앙...렉서 모두 수정해야 되는 건가...

**Comment by Giromi** [comment]
아 렉서에서는 소괄호 flag안쓰넹..?

**Comment by Giromi** [comment]
set_parentheses_flag함수 수정
