### ISSUE TITLE
PART : Lexer

### ISSUE THREAD

**Issue by Giromi** [Oris482/Minishell#5]
# To Do list
- [x] flow chart 구조 제작하기
- [x] readline을 통해 들어온 문자 리스트

**Comment by Oris482** [comment]
Norm Issue #13

**Comment by Giromi** [comment]
# 8/30 회의 내용

## 에러 해결 부분
- [ ] get_files_cur_pwd 함수 개수 0일 때 에러처리
- [ ] recursive_find_files files == NULL이면 return ;
- [ ] Makefile lldb cp 부분 추가

**Comment by Giromi** [comment]
## 에러 해결 부분 회의 필요
- [ ] get_files_cur_pwd 함수 개수 0일 때 에러처리
- [ ] recursive_find_files files == NULL이면 return ;
- [ ] Makefile lldb cp 부분 추가
- [ ] ./*/ 앞부분 경로 들어왔을 시 대응 필요
- [ ] 경로 바뀌었을 때 받을 수 있도록 해야 함. 지금은 현재 경로 내에 있는 것만?
- [ ] ft_split `test*/` 예제 처리 ⇒ idx가 1까지만 증가해야 함
- [ ] ft_strcnt cnt_flag 필요
- [ ] wildcard 없으면 splited 안해도?

**Comment by Giromi** [comment]
### 2022.08.31 minsuki2 할일

- [ ] my_opendir  빈 문자열 처리
- [ ] 
- [ ]
