### ISSUE TITLE
HELP : len 부분 int로 바꿔도 되는 지?

### ISSUE THREAD

**Issue by Giromi** [Oris482/Minishell#8]
![image](https://user-images.githubusercontent.com/60354633/186039449-1b19dec4-5a21-44f5-adea-d4d7d9cefb32.png)

ft_strcpy 함수에서 len을 size_t로 해야 되는 다른 이유가 있는 지?

없으면 int 형으로 바꿔도 되는 지?

**Comment by Oris482** [comment]
음수가 될 수 없다는 뜻이였습니다. int도 상관없어요
